---
# Ansible playbook for a GL server.
# @todo - Install postfix `yum -y install postfix`.
- hosts: gitlab
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - ehime.firewall
    - ehime.gitlab
